### PR TITLE
Sr coach checkbox rebased

### PR DESCRIPTION
**Pull request by til**
The branch SR-coach-checkbox in #338 could not be merged, because master has changed in the meantime. So I created this new branch, SR-coach-checkbox-rebased, rebased on an updated master.

@sareg0 or @PragTob can you have a look if this looks ok, and if yes, merge this one, and then close #338?

### CODE REVIEW

**Comment by berlintam** [comment]
woot woot! are there any plans to link to the coaches index from the app itself so that ppl can see who is available for coaching?

If so, I'd change the header on the coaches index to be something like 'list of available RG workshop coaches'.

and then maybe later we can ask these ppl for their email addresses & cities so that they can be contacted easily by the correct ppl. But that's for a later PR :)

AWESOME JOB @sareg0 WOOOOOT!

(remember to close this PR with a gif :smile: )

**Comment by sareg0** [comment]
yes, I think we are breaking it up into steps, because... well snail pace atm for me, so I figure we'll get one piece done, then work on each teensy eensy advancement from there. It will all tie into the larger feature, wich will be a list of coaches, that one can filter, then a method of contact. I will let the powers that be decide whether it is mergable, but I have a gif at the ready for post merge :)

**Comment by berlintam** [comment]
cool beanz! I'm pro-merge :)

**Comment by lislis** [comment]
+1

**Comment by berlintam** [comment]
MERGE ITTTTTT!

**Comment by sareg0** [comment]
!()[http://televisomnia.tumblr.com/post/124200532873/espn-celebrates-23rd-annual-espy-awards]

**Pull request merged**
