### PR TITLE
Add autostart script to git

### PR DESCRIPTION
**Pull request by lislis**

### CODE REVIEW

**Comment by til** [comment]
👍 

if someone else wants to deploy: please do, but make sure that the currently not checked in `config/autostart` on production is not in the way, maybe by removing it manually before doing the deploy.

**Comment by lislis** [comment]
I deleted the `config/autostart` form uberspace and push current master.
After a few moments of downtime we app restarted. 
Seems to work. YAY
working

**Comment by vsmart** [comment]
cat yay

**Comment by til** [comment]
Yaaaaay, well done! 🚀

**Pull request merged**
