### PR TITLE
update rails

### PR DESCRIPTION
**Pull request by lislis**
I bundle updated to see what happens.
@berlintam you wanna take it from here ;)

### CODE REVIEW

**Comment by berlintam** [comment]
:scream:

**Comment by lislis** [comment]
@berlintam awesome!
finger guns

**Comment by berlintam** [comment]
thanks! I dunno if it'll break stuff thou... I mean... I clicked around & everything seemed ok but you never know. Should we just #yolomerge?

**Comment by til** [comment]
I merged, should I deploy too or does somebody else want to?

**Pull request merged**
