### PR TITLE
Remove Rolify & add admin boolean to users ALL IN ONE GO!

### PR DESCRIPTION
**Pull request by berlintam**
this is step2!

One question: should anything be done about this migration?
https://github.com/rubycorns/rorganize.it/blob/master/db/migrate/20140517093641_rolify_create_roles.rb

If so... wat?

### CODE REVIEW

**Comment by PragTob** [comment]
As you did, drop the role table then all should be good :D

**Comment by berlintam** [comment]
@PragTob are you psychic!? You commented literally at the exact moment I pushed the commit to drop the tables!

**Comment by PragTob** [comment]
tobi reads minds

**Comment by berlintam** [comment]
so, NEW PLAN!

everything is in one super awesome migration now. So the two PRs aren't needed anymore!
Instead, let's just merge this one and ditch the other one.

**Comment by til** [comment]
Merged!

**Comment by berlintam** [comment]
thanks for the help @til!

station

**Pull request merged**
