### PR TITLE
Sr pagination 232

### PR DESCRIPTION
**Pull request by sareg0**
This is a new attempt at this forward and back button mess on the blog post show page.

We need to update the scope to not order things, but we are concerned that other things are dependant on it. It would be great to have a thorough look over this, and really check how deep the rabbit hole has gone. Who knew forward and back buttons were so complicated :)

### CODE REVIEW

**Comment by til** [comment]
A short note on scopes: they are nothing super-magic or god-given, but
simply small helper methods that can be used to make the code that calls
them more intention revealing. ("intention revealing" is indeed a magic
phrase when describing code btw ;-))

So e.g. code in the controller without scopes would look like this:

  @posts = Post.where(draft: false).order(:published_at: :desc)

which contains a lot of technical details that are not immediately
understandable to the reader, and also not really relevant in the
context of the controller. In contrast, with an appropriately named
scope the code could like this:

  @posts = Post.published_ordered_newest_first

The name of this scope is long, but in my opinion easier to understand
than the version above. Feel free to come up with an even better name.

So I suggest to create more scopes for Post, and name them intention
revealing, in particular make it clear which ones include an order
clause.

Bonus points for reusing a previously defined scope in a scope
definition!

**Comment by sareg0** [comment]
Okay @til with the help of @berlintam I created some more scope. You can see these in the latest commit. Can you tell me if I'm on the right track?

**Comment by til** [comment]
Looks good to me, this is on the right track!

What else is missing? Specs are failing it seems.

**Comment by sareg0** [comment]
Hey @til, thanks to the awesome help of the corns, I made the improvements to the spec that you recommended. The only wrinkle is that the build isn't passing, and we couldn't pinpoint why exactly. Do you think you could provide a little guidance?

**Comment by til** [comment]
So it says, travis-ci/push is failing, but travis-ci/pr is passing. If I understand correctly, this means that if one checks out the branch of this PR, SR-pagination-232, then all specs pass. However, if one simulates what would happen if the PR was merged, ie. merge the branch SR-pagination-232 into master, then some specs fail.

This would mean that something has changed in master, which now conflicts with your changes. The first step to fix this would be to bring this PR to the latest state of master, e.g. by merging master into the branch, or better, rebase it against a current master (`git rebase master` with the feature branch checked out, after everything is pulled to be up to date).

**Comment by til** [comment]
And then check if the specs fail locally in the same way as on Travis. If yes, fix them :grinning:

**Comment by sareg0** [comment]
At the advice of @berlintam we did rebase to master. I was on my branch and did 'git rebase master'.
Is this all that needed to be done, or did one need to do 'git pull' as well?
Again, there were no failures. I guess that's why we were puzzled.

**Comment by berlintam** [comment]
@sareg0 ya, you need to pull master to get the latest master first. Otherwise you'll still be working with the old master that has been lying around on your computer for possibly a few weeks & that won't reflect the possibly failing changes. So first checkout onto master, pull it, then go back to your branch & rebase. Hopefully you'll then be able to recreate the failing specs. :fingerscrossed:

**Comment by sareg0** [comment]
oh cool! I had not done the pull on maser I don't think. So I did that, and rebased my branch on it... Still '0' failures... WHYYYY?! Why won't you fail?!

**Comment by berlintam** [comment]
:scream:

**Comment by til** [comment]
Maybe the rebase fixed the errors magically. If so, then a "git push -f"
(with your branch checked out) triggering a new Travis run should then
not fail anymore.

**Comment by sareg0** [comment]
i'll give it a shot

**Comment by berlintam** [comment]
OMG LOOK AT THAT!

**Comment by sareg0** [comment]
OH OH OH OH OH!!! It worrrrrrkeeeeeedddd!!

**Comment by sareg0** [comment]
i need to squash it all now, so I'll do that once I get home

**Comment by sareg0** [comment]
oopps... totes forgot to squash. Okay... now... I am hoping I managed to squash properly.
@berlintam or @til or whoever, if you wanna take a gander to make sure it's all good, I would be so appreciative.

**Comment by til** [comment]
According to

https://github.com/rubycorns/rorganize.it/pull/409/commits

there are currently still 9 commits in this PR, so it looks like the
squashing did not have the expected effect.

Off the top of my head, these are the steps to rebase and squash:

git checkout master
git pull
git checkout SR-pagination-232
git rebase -i master
... edit all but first line to "squash" ...
... edit new commit message for remaining single commit ...
git push -f


(please review critically, don't paste blindly)

**Comment by berlintam** [comment]
@sareg0 maybe you just didn't force push at the end?
(the `gif push -f` part til mentioned.)

**Comment by sareg0** [comment]
uh oh... I think I did... I just pushed. Now, when I try the squash I'm in trouble with some conflicts. I'll give it a go by myself, and schrei for help if I need it.

**Comment by sareg0** [comment]
BOOYYAAAAA!!! I think I did it!

**Comment by til** [comment]
Wohoo, you did it! Squashing worked!

But now 2 specs are broken again ...

**Comment by lislis** [comment]
#yolo

**Comment by berlintam** [comment]
yolo

**Pull request merged**
