### PR TITLE
Add members to group

### PR DESCRIPTION
**Pull request by raluka**
Until now, inside seeds, we create users and groups, but groups are empty. 
This PR aims to improve database seed info, by adding existing users to "The Rubycorns" group.

### CODE REVIEW

**Comment by raluka** [comment]
Thank you for feed-back! I agree PR description is poor, I'll improve it asap. Same for extra line, will be deleted :)

**Comment by til** [comment]
Cool. Feel free to force-push a changed commit to this branch, in my
understanding that is OK to do in PRs (in case you don't know what I
mean, please ask).

**Comment by sareg0** [comment]
I'd be happy to merge this once those changes are made!

**Comment by sareg0** [comment]
https://media.giphy.com/media/l2Sqir5ZxfoS27EvS/giphy.gif

**Pull request merged**
