### PR TITLE
move actions to subnav

### PR DESCRIPTION
**Pull request by lislis**
#### Is this solving an issue already in our backlog? If so, please mention which one
It belongs to #597 

## Before

screenshot-2018-6-5 rorganize it find a rails girls study group 1

## After

screenshot-2018-6-5 rorganize it find a rails girls study group

### CODE REVIEW

**Comment by PragTob** [comment]
:+1: 

Looking good, the "account linked with github" looks a bit too much like a menu item imo though so I'd expect to be able to click it? Maybe we just remove it from there and display it somewhere else?

**Comment by lislis** [comment]
I had the same feeling.
Maybe it's better to move the information to the edit page anyway? Give it a box for 'Link account to GH | Account linked with GH'

**Comment by PragTob** [comment]
I think that's a good idea, yeah!

**Comment by lislis** [comment]
moved the GH account linking to person#edit

screenshot-2018-7-3 rorganize it find a rails girls study group 1
screenshot-2018-7-3 rorganize it find a rails girls study group

**Comment by lislis** [comment]
MERGING THIS
selfmerge

**Pull request merged**
