### PR TITLE
fixing ugly error messages

### PR DESCRIPTION
**Pull request by sareg0**

### CODE REVIEW

**Comment by til** [comment]
:+1: from looking at the code. I haven't checked it out and tested it for real, but I suppose it does what is expected.

**Comment by sareg0** [comment]
yeah. TBH @PragTob found out what to do also. I think there are more improvements that could be made. Should I push the other changes into one PR, or shall I just plug away at them and we merge regularly?

**Comment by til** [comment]
I don't know ;-). Does this one change in itself have a visible and
desired effect already, or is it only the preparation for something
else? If it is useful in itself, then I suggest merging it now. And for
simplicity, later reopen this PR and continue in it.

**Comment by sareg0** [comment]
Yes it has the desired outcome :)

On Wednesday, 29 July 2015, Tilmann Singer <notifications@github.com> wrote:

> I don't know ;-). Does this one change in itself have a visible and
> desired effect already, or is it only the preparation for something
> else? If it is useful in itself, then I suggest merging it now. And for
> simplicity, later reopen this PR and continue in it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubycorns/rorganize.it/pull/360#issuecomment-125988807>
> .
>


-- 
Kindest Regards,
Sara and the Rails Girls Summer of Code Team
@RailsGirlsSoC <https://twitter.com/RailsGirlsSoC>

Kindest Regards,
Sara
@sareg0 <https://twitter.com/sareg0>
+49(0)17699393251

**Comment by til** [comment]
mrrrgd then ;-)

**Pull request merged**
