### PR TITLE
add alphabetical jump links to people/coach index pages

### PR DESCRIPTION
**Pull request by berlintam**
This is semi-resolving issue #370 
I added alphabetical jump links for the people and coaches index pages, exciting stuff! I also refactored a bit as there was a lot of repetition between the people#index and the coach#index. I pulled a bunch of it out into partials. 
I'm only working in the non-redesign area thou, as I don't want to touch the redesign stuff until it's up and running & for realz. But since this is mostly in partials, switching it over to the redesign when ready shouldn't be much of a problem. 

I have no specs, as it's mostly display stuff & I don't really want to write a feature spec for this. But maybe a little bit of a controller spec? Thoughts?

Anyway, here's a screenshot:
screenshot from 2017-02-07 16-35-29

As always, review & comments always welcome!

### CODE REVIEW

**Comment by lislis** [comment]
This is awesome! Write a test if you want but I think this is great already! Especially how you generate the alphabetical list :D

**Comment by berlintam** [comment]
woot woot! thanks @lislis. ya, I was pretty stoked about it as well :smile:

**Comment by berlintam** [comment]
giphy

**Comment by til** [comment]
That looks great, someone should deploy!

**Pull request merged**
