### PR TITLE
Super Fancy Map Markers

### PR DESCRIPTION
**Pull request by lislis**
Sarah and I tried to make map markers on the command line. And that worked!
Now we need to do that in carrierware/ minimagick dsl. HELP!

### CODE REVIEW

**Comment by PragTob** [comment]
This is a bit old... but any chance we can get it back up to speed again? :D

**Comment by lislis** [comment]
Plan was actually to ditch this PR and then start fresh with the dragonfly gem. This is more or less or reference

**Comment by PragTob** [comment]
If it is more or less a reference I'll close it, it can still be found, the branch is ther,e but just closed so we are not confused :)

**Comment by lislis** [comment]
that's cool. This needs to be redone completely anyway

**Pull request closed without merging**
