### PR TITLE
added emoji gem and assets

### PR DESCRIPTION
**Pull request by sareg0**
As per issue #137, we have integrated 'emoji' gem from Steve Klabnik. 
We did not succeed in allowing users to write a word and get the emoji back, so this may be the second step in solving this issue.
If you would like to test it out, you can simple use and image tag and link to the images in 'assets/emoji'. Maybe there is a method but we could not find it. 

Can't wait to use a ridiculous gif if this gets merged :D

### CODE REVIEW

**Comment by PragTob** [comment]
What's the status of this? Can we haz merge?

**Comment by sareg0** [comment]
hmm... well there is a bit of a little problem.
Once we added the things, it seems that there are some groups that won't update. Other groups DO update and have the emojis, and then some groups update but DON'T parse the emojis

WAAAT!

**Comment by lislis** [comment]
So the thing is still the renderer @PragTob. The MdEmoji renderer inherits from the Base renderer, but actually we would need it to inherit from the HTML renderer. Ideas? Suggestions?

**Comment by PragTob** [comment]
But.. MdEmoji inherits from the HTML one, no?

`class Render < Redcarpet::Render::HTML` ? https://github.com/elm-city-craftworks/md_emoji/blob/master/lib/md_emoji/render.rb

**Comment by lislis** [comment]
Hmm. But then, why doesn't it work?

**Pull request merged**
