### PR TITLE
Group thump picture bigger in order to not get pixely

### PR DESCRIPTION
**Pull request by Malwine**
Fixes the pixelation of the group thumb pics.

### CODE REVIEW

**Comment by Malwine** [comment]
Sorry I didn't read the issue...
https://github.com/rubycorns/rorganize.it/issues/466

**Comment by Malwine** [comment]
We can still merge this.

**Comment by Malwine** [comment]
Pleaseeeeeee

**Comment by Malwine** [comment]
Come on @til

**Comment by til** [comment]
hm ok

**Comment by Malwine** [comment]
giphy 2

**Comment by til** [comment]
but #466 is still relevant

**Pull request merged**
