### PR TITLE
Fix filter bug

### LINKED ISSUE #420: filter bug on rorganize.it/groups
Hey,
I found one bug in the group section on rorganize.it
When you search for groups in specific cities/countries and you get the result, the filter doesn't allow you to search for other groups in other places afterwards (-> screenshot below).
bug_filter_rorganize

### PR DESCRIPTION
**Pull request by marjal**
fixes #420

### CODE REVIEW

**Comment by til** [comment]
Cool, thanks for looking into this. :+1:

I suggest that you first press the merge button over there: https://github.com/marjal/rorganize.it/pull/1 , and once that is done, we merge this pull request here into rorganize.it. This way, the change will be in all 3 controllers at once.

**Comment by roschaefer** [comment]
*bump* would be a good motivation for us if we see this in the master branch tomorrow evening.. :+1:

**Comment by berlintam** [comment]
hey @roschaefer, we're meeting tomorrow evening so we'll be sure to take a look at it!

**Comment by til** [comment]
I think it can be merged already, hope that's ok for everyone.

**Pull request merged**
